package com.dp.advancedgunnerycontrol.weapontags

internal object EditableWeaponTagFluxDefinitions {
    fun definitions(): List<EditableWeaponTagDefinition> = listOf(
        fluxThresholdDefinition(
            id = "hold_fire_flux_threshold",
            family = "HoldFire",
            representativeTemplateTag = "HoldFire(TF>N%)",
            acceptedTemplateTags = setOf("HoldFire(TF>N%)", "HoldFire(SF>N%)", "HoldFire(HF>N%)"),
            comparator = ">",
            thresholdMinimum = 0,
            thresholdMaximum = 99,
            defaultMetric = "TF",
            defaultThreshold = 25,
            exclusivityPrefix = "HoldFire",
            includeTotalFluxCap = true,
            totalFluxCapAllowedMetricIds = setOf("SF"),
            includeRecentBeamException = true,
        ),
        fluxThresholdDefinition(
            id = "force_fire_flux_threshold",
            family = "Force",
            representativeTemplateTag = "Force(TF<N%)",
            acceptedTemplateTags = setOf("Force(TF<N%)", "Force(SF<N%)", "Force(HF<N%)"),
            comparator = "<",
            thresholdMinimum = 0,
            thresholdMaximum = 99,
            defaultMetric = "TF",
            defaultThreshold = 25,
            exclusivityPrefix = "Force",
            includeTotalFluxCap = true,
        ),
        shieldThresholdDefinition(
            id = "avoid_shield_target_threshold",
            family = "AvoidShield",
            representativeTemplateTag = "AvoidShield(S<N%)",
            acceptedTemplateTags = setOf("AvoidShield", "AvoidShield+", "AvoidShield(S<N%)"),
            comparator = "<",
            defaultThresholdProvider = ::avoidShieldDefaultPercent,
            aliasThresholds = mapOf("AvoidShield+" to 2),
            exclusivityPrefix = "AvoidShield:S",
        ),
        shieldThresholdDefinition(
            id = "target_shield_target_threshold",
            family = "TargetShield",
            representativeTemplateTag = "TargetShield(S>N%)",
            acceptedTemplateTags = setOf("TargetShield", "TargetShield+", "TargetShield(S>N%)"),
            comparator = ">",
            defaultThresholdProvider = ::targetShieldDefaultPercent,
            aliasThresholds = mapOf("TargetShield+" to 1),
            exclusivityPrefix = "TargetShield:S",
        ),
        fluxThresholdDefinition(
            id = "avoid_shield_flux_threshold",
            family = "AvoidShield",
            representativeTemplateTag = "AvoidShield(TF>N%)",
            acceptedTemplateTags = setOf("AvoidShield(TF>N%)", "AvoidShield(SF>N%)", "AvoidShield(HF>N%)"),
            comparator = ">",
            thresholdMinimum = 0,
            thresholdMaximum = 99,
            defaultMetric = "TF",
            defaultThreshold = 10,
            exclusivityPrefix = "AvoidShield",
            includeTotalFluxCap = true,
            targetShieldThresholdComparator = "<",
            defaultTargetShieldThresholdProvider = ::avoidShieldDefaultPercent,
            includeDamageTypeExclusions = true,
        ),
        fluxThresholdDefinition(
            id = "target_shield_flux_threshold",
            family = "TargetShield",
            representativeTemplateTag = "TargetShield(TF>N%)",
            acceptedTemplateTags = setOf("TargetShield(TF>N%)", "TargetShield(SF>N%)", "TargetShield(HF>N%)"),
            comparator = ">",
            thresholdMinimum = 0,
            thresholdMaximum = 99,
            defaultMetric = "TF",
            defaultThreshold = 10,
            exclusivityPrefix = "TargetShield",
            includeTotalFluxCap = true,
            targetShieldThresholdComparator = ">",
            defaultTargetShieldThresholdProvider = ::targetShieldDefaultPercent,
            includeDamageTypeExclusions = true,
        ),
        fluxThresholdDefinition(
            id = "pd_flux_threshold",
            family = "PD",
            representativeTemplateTag = "PD(TF>N%)",
            acceptedTemplateTags = setOf("PD(TF>N%)", "PD(SF>N%)", "PD(HF>N%)"),
            comparator = ">",
            thresholdMinimum = 0,
            thresholdMaximum = 99,
            defaultMetric = "TF",
            defaultThreshold = 50,
            exclusivityPrefix = "PD"
        )
    )
}
