package com.dp.advancedgunnerycontrol.weapontags

fun tagNameToRegexName(tag: String): String =
    WeaponTagNameCache.template(tag) { tagNameToRegexNameUncached(tag) }

private fun tagNameToRegexNameUncached(tag: String): String {
    val canonicalTag = canonicalizeWeaponTagName(tag)
    return when {
        holdTotalFluxRegex.matches(canonicalTag) -> "HoldFire(TF>N%)"
        holdSoftFluxRegex.matches(canonicalTag) -> "HoldFire(SF>N%)"
        holdHardFluxRegex.matches(canonicalTag) -> "HoldFire(HF>N%)"
        forceFireTotalFluxRegex.matches(canonicalTag) -> "Force(TF<N%)"
        forceFireSoftFluxRegex.matches(canonicalTag) -> "Force(SF<N%)"
        forceFireHardFluxRegex.matches(canonicalTag) -> "Force(HF<N%)"
        avoidShieldDamageExclusionRegex.matches(canonicalTag) -> "AvoidShield"
        avoidShieldThresholdRegex.matches(canonicalTag) -> "AvoidShield(S<N%)"
        avoidShieldTotalFluxRegex.matches(canonicalTag) -> "AvoidShield(TF>N%)"
        avoidShieldSoftFluxRegex.matches(canonicalTag) -> "AvoidShield(SF>N%)"
        avoidShieldHardFluxRegex.matches(canonicalTag) -> "AvoidShield(HF>N%)"
        targetShieldDamageExclusionRegex.matches(canonicalTag) -> "TargetShield"
        targetShieldThresholdRegex.matches(canonicalTag) -> "TargetShield(S>N%)"
        targetShieldTotalFluxRegex.matches(canonicalTag) -> "TargetShield(TF>N%)"
        targetShieldSoftFluxRegex.matches(canonicalTag) -> "TargetShield(SF>N%)"
        targetShieldHardFluxRegex.matches(canonicalTag) -> "TargetShield(HF>N%)"
        pdSoftFluxRegex.matches(canonicalTag) -> "PD(SF>N%)"
        pdTotalFluxRegex.matches(canonicalTag) -> "PD(TF>N%)"
        pdHardFluxRegex.matches(canonicalTag) -> "PD(HF>N%)"
        canonicalTag == "ConserveAmmo" -> "Opportunist(A<N%)"
        opportunistAmmoRegex.matches(canonicalTag) -> "Opportunist(A<N%)"
        opportunistTunedRegex.matches(canonicalTag) -> "Opportunist"
        canonicalTag == "ConservePDAmmo" -> "PD(A<N%)"
        pdAmmoRegex.matches(canonicalTag) -> "PD(A<N%)"
        canonicalTag == "PrioSmall(N)" -> "PrioSmall"
        prioSmallRegex.matches(canonicalTag) -> "PrioSmall"
        canonicalTag == "PrioSmall" -> "PrioSmall"
        canonicalTag == "PrioFighter(N)" -> "PrioFighter"
        prioFighterRegex.matches(canonicalTag) -> "PrioFighter"
        canonicalTag == "PrioMissile(N)" -> "PrioMissile"
        prioMissileRegex.matches(canonicalTag) -> "PrioMissile"
        canonicalTag == "PrioShip(N)" -> "PrioShip"
        prioShipRegex.matches(canonicalTag) -> "PrioShip"
        canonicalTag == "PrioFocused(N)" -> "PrioFocused"
        prioFocusedRegex.matches(canonicalTag) -> "PrioFocused"
        prioWoundedDamageExclusionRegex.matches(canonicalTag) -> "PrioWounded"
        targetPhaseDamageExclusionRegex.matches(canonicalTag) -> "TargetPhase"
        avoidPhasedDamageExclusionRegex.matches(canonicalTag) -> "AvoidPhased"
        prioShieldsDamageExclusionRegex.matches(canonicalTag) -> "PrioShields"
        canonicalTag == "PrioShields(N)" -> "PrioShields"
        prioShieldsRegex.matches(canonicalTag) -> "PrioShields"
        prioHullDamageExclusionRegex.matches(canonicalTag) -> "PrioHull"
        canonicalTag == "PrioHull(N)" -> "PrioHull"
        prioHullRegex.matches(canonicalTag) -> "PrioHull"
        canonicalTag == "PrioClose(N)" -> "PrioClose"
        prioCloseRegex.matches(canonicalTag) -> "PrioClose"
        canonicalTag == "PrioFar(N)" -> "PrioFar"
        prioFarRegex.matches(canonicalTag) -> "PrioFar"
        parseSyncTagOptions(canonicalTag) != null -> parseSyncTagOptions(canonicalTag)?.family ?: canonicalTag
        canonicalTag == "TargetBig" -> "TargetBig"
        canonicalTag == "TargetSmall" -> "TargetSmall"
        noPdWasteRegex.matches(canonicalTag) -> "AvoidPD(Waste>N%)"
        noPdHealthRegex.matches(canonicalTag) -> "AvoidPD(H<N)"
        canonicalTag == "IgnoreMinorPD" -> "AvoidPD(H<N)"
        avoidArmorRegex.matches(canonicalTag) -> "AvoidArmor"
        panicFireRegex.matches(canonicalTag) -> "Panic"
        rangeRegex.matches(canonicalTag) -> "Range"
        rofRegex.matches(canonicalTag) -> "LowRoF(N%)"
        else -> canonicalTag
    }
}
